django_library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library_app.urls')),
    path('users/', include('users.urls')),
]

library_app/urls.py
"""URL schemes for the "library_app" app."""

from . import views
from django.urls import path


app_name = "library_app"
urlpatterns = [
	# Домашняя страница.
	path('', views.index, name="index"),
	# Страница для добавления книг.
	path('new_book/', views.new_book, name="new_book"),
	# Страница для добавления песен.
	path('new_song/', views.new_song, name="new_song"),
	# Страница для добавления фото.
	path('new_photo/', views.new_photo, name="new_photo"),
	# Страница для добавления видео.
	path('new_video/', views.new_video, name="new_video"),
	# Страница для просмотра всех книг.
	path('view_all_books/', views.view_all_books, name="view_all_books"),
	# Страница для просмотра всех песен.
	path('view_all_songs/', views.view_all_songs, name="view_all_songs"),
	# Страница для просмотра всех фото.
	path('view_all_photos', views.view_all_photos, name="view_all_photos"),
	# Страница для просмотра всех видео.
	path('view_all_videos/', views.view_all_videos, name="view_all_videos"),
	# Страница для просмотра конкретной книги.
	path('view_book/<int:book_id>', views.view_book, name="view_book"),
	# Страница для просмотра конкретной песни.
	path('view_song/<int:song_id>', views.view_song, name="view_song"),
	# Страница для просмотра конкретного фото.
	path('view_photo/<int:photo_id>', views.view_photo, name="view_photo"),
	# Страница для просмотра конкретного видео.
	path('view_video/<int:video_id>', views.view_video, name="view_video"),
]

users/urls.py
"""URL schemes for the "users" app."""

from django.urls import path, include
from . import views


app_name = "users"
urlpatterns = [
	# Включить URL авторизаций по умолчанию.
	path('', include('django.contrib.auth.urls')),
	# Страница регистраций.
	path('register/', views.register, name="register"),
]

library_app/models.py
from django.db import models
from django.contrib.auth.models import User


class AddBook(models.Model):
	"""Модель для добавления книг."""
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=150)
	author = models.CharField(max_length=50, blank=True)
	book = models.FileField(upload_to="books/%Y/%m/%d/")
	publication_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Возвращает строковое представление модели."""
		return self.title


class AddSong(models.Model):
	"""Модель для добавления песен."""
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	author = models.CharField(max_length=50, blank=True)
	song = models.FileField(upload_to="songs/%Y/%m/%d/")
	publication_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Возвращает строковое представление модели."""
		return self.title


class AddPhoto(models.Model):
	"""Модель для добавления фотографий."""
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=150)
	photo = models.ImageField(upload_to="photos/%Y/%m/%d/")
	publication_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Возвращает строковое представление модели."""
		return self.title


class AddVideo(models.Model):
	"""Модель для добавления фотографий."""
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=150)
	video = models.FileField(upload_to="videos/%Y/%m/%d/")
	publication_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		"""Возвращает строковое представление модели."""
		return self.title

library_app/forms.py
from django import forms
from .models import (
	AddBook,
	AddSong,
	AddPhoto,
	AddVideo
)


class AddBookForm(forms.ModelForm):
	"""Форма для добавления книг."""
	class Meta:
		model = AddBook
		fields = ['title', 'author', 'book']
		labels = {'title': 'Название', 'author': 'Автор', 'book': 'Книга'}


class AddSongForm(forms.ModelForm):
	"""Форма для добавления песен."""
	class Meta:
		model = AddSong
		fields = ['title', 'author', 'song']
		labels = {'title': 'Название', 'author': 'Автор', 'song': 'Песня'}


class AddPhotoForm(forms.ModelForm):
	"""Форма для добавления фото."""
	class Meta:
		model = AddPhoto
		fields = ['title', 'photo']
		labels = {'title': 'Название', 'photo': 'Фото'}


class AddVideoForm(forms.ModelForm):
	"""Форма для добавления фотографий."""
	class Meta:
		model = AddVideo
		fields = ['title', 'video']
		labels = {'title': 'Название', 'video': 'Видео'}

library_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import Http404
from datetime import datetime

from .models import (
	AddBook,
	AddSong,
	AddPhoto,
	AddVideo
)
from .forms import (
	AddBookForm,
	AddSongForm,
	AddPhotoForm,
	AddVideoForm
)


def index(request):
	"""Домашняя страница."""
	return render(request, 'library_app/index.html')

@login_required
def new_book(request):
	"""Добавляет новую книгу."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = AddBookForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = AddBookForm(request.POST, request.FILES)
		if form.is_valid():
			new_book = form.save(commit=False)
			new_book.user = request.user
			new_book.save()
			return redirect('library_app:index')

	# Вывести пустую или недействительную форму.
	context = {'form': form}
	return render(request, 'library_app/new_book.html', context)


@login_required
def new_song(request):
	"""Добавляет новую песню."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = AddSongForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = AddSongForm(request.POST, request.FILES)
		if form.is_valid():
			new_song = form.save(commit=False)
			new_song.user = request.user
			new_song.save()
			return redirect('library_app:index')

	# Вывести пустую или недеqствительную форму.
	context = {'form': form}
	return render(request, 'library_app/new_song.html', context)


@login_required
def new_photo(request):
	"""Добавляет новое фото."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = AddPhotoForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = AddPhotoForm(request.POST, request.FILES)
		if form.is_valid():
			new_photo = form.save(commit=False)
			new_photo.user = request.user
			new_photo.save()
			return redirect('library_app:index')

	# Вывести пустую или недействительную форму.
	context = {'form': form}
	return render(request, 'library_app/new_photo.html', context)


@login_required
def new_video(request):
	"""Добавляет новое видео."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = AddVideoForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = AddVideoForm(request.POST, request.FILES)
		if form.is_valid():
			new_video = form.save(commit=False)
			new_video.user = request.user
			new_video.save()
			return redirect('library_app:index')

	# Вывести пустую или недействительную форму.
	context = {'form': form}
	return render(request, 'library_app/new_video.html', context)


@login_required
def view_all_books(request):
	"""Просмотр добавленных книг."""
	# Берем из БД все добавленные книги.
	all_books = AddBook.objects.all()[::-1]
	db_info = None
	error_info = None

	# Проверяем не пусто ли наше БД.
	if len(all_books) != 0:
		db_info = all_books
	else:
		error_info = "Вы еще не добавили данные в БД."

	context = {'db_info': db_info, 'error_info': error_info}
	return render(request, 'library_app/view_all_books.html', context)


@login_required
def view_all_songs(request):
	"""Просмотр добавленных песен."""
	# Берем из БД все добавленные книги.
	all_songs = AddSong.objects.all()[::-1]
	db_info = None
	error_info = None

	# Проверяем не пусто ли наше БД.
	if len(all_songs) != 0:
		db_info = all_songs
	else:
		error_info = "Вы еще не добавили данные в БД."

	context = {'db_info': db_info, 'error_info': error_info}
	return render(request, 'library_app/view_all_songs.html', context)


@login_required
def view_all_photos(request):
	"""Просмотр добавленных песен."""
	# Берем из БД все добавленные книги.
	all_photos = AddPhoto.objects.all()[::-1]
	db_info = None
	error_info = None

	# Проверяем не пусто ли наше БД.
	if len(all_photos) != 0:
		db_info = all_photos
	else:
		error_info = "Вы еще не добавили данные в БД."

	context = {'db_info': db_info, 'error_info': error_info}
	return render(request, 'library_app/view_all_photos.html', context)


@login_required
def view_all_videos(request):
	"""Просмотр добавленных песен."""
	# Берем из БД все добавленные книги.
	all_videos = AddVideo.objects.all()[::-1]
	db_info = None
	error_info = None

	# Проверяем не пусто ли наше БД.
	if len(all_videos) != 0:
		db_info = all_videos
	else:
		error_info = "Вы еще не добавили данные в БД."

	context = {'db_info': db_info, 'error_info': error_info}
	return render(request, 'library_app/view_all_videos.html', context)


@login_required
def view_book(request, book_id):
	"""Просмотр конкретной книги."""
	book = AddBook.objects.get(id=book_id)
	return render(request, 'library_app/view_book.html', {'book': book})


@login_required
def view_song(request, song_id):
	"""Просмотр конкретной песни."""
	song = AddSong.objects.get(id=song_id)
	return render(request, 'library_app/view_song.html', {'song': song})


@login_required
def view_photo(request, photo_id):
	"""Просмотр конкретной книги."""
	photo = AddPhoto.objects.get(id=photo_id)
	return render(request, 'library_app/view_photo.html', {'photo': photo})


@login_required
def view_video(request, video_id):
	"""Просмотр конкретного видео."""
	video = AddVideo.objects.get(id=video_id)
	return render(request, 'library_app/view_video.html', {'video': video})

library_app/templates/library_app/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Django Library</title>
	<link rel="stylesheet" type="text/css" href="{% static 'library_app/base.css' %}">
</head>
<body>
	<h1><a href="{% url 'library_app:index' %}">Django Library</a></h1>

	<div class="registration">
		{% if user.is_authenticated %}
			Hi, {{ user.username }}
			<a href="{% url 'users:logout' %}">выйти</a>
		{% else %}
			<a href="{% url 'users:login' %}">Войти</a>
			<a href="{% url 'users:register' %}">Зарегестрироваться</a>
		{% endif %}
	</div>

	<div>
		<b>
			<a href="{% url 'library_app:new_book' %}">Добавить книгу</a> —
			<a href="{% url 'library_app:new_song' %}">Добавить песню</a> —
			<a href="{% url 'library_app:new_photo' %}">Добавить фото</a> —
			<a href="{% url 'library_app:new_video' %}">Добавить видео</a>
		</b>
	</div>

	<!-- Add red line. -->
	<hr>

	{% block content %}
	{% endblock %}

</body>
</html>

library_app/templates/library_app/index.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Всем привет, это главная страница.</h2>
	{% if user.is_authenticated %}
		<h3>Просмотреть добавленные мною данные:</h3>
		<a href="{% url 'library_app:view_all_books' %}">Книги</a> —
		<a href="{% url 'library_app:view_all_songs' %}">Песни</a> —
		<a href="{% url 'library_app:view_all_photos' %}">Фото</a> —
		<a href="{% url 'library_app:view_all_videos' %}">Видео</a>
	{% else %}
		<p>Вы либо не зарегестрировались, либо не вошли в свой акканут. Пожалуйста, <a href="{% url 'users:login' %}">войдите</a> или <a href="{% url 'users:register' %}">зарегестрируйтесь</a>.</p>
	{% endif %}
{% endblock %}

library_app/templates/library_app/new_book.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Добавление книг.</h2>
	
	<form action="{% url 'library_app:new_book' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">добавить</button>
	</form>
{% endblock %}

library_app/templates/library_app/new_photo.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Добавление фото.</h2>

	<form action="{% url 'library_app:new_photo' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">добавить</button>
	</form>
{% endblock %}

library_app/templates/library_app/new_song.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Добавление песен.</h2>

	<form action="{% url 'library_app:new_song' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">добавить</button>
	</form>
{% endblock %}

library_app/templates/library_app/new_video.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Добавление видео.</h2>

	<form action="{% url 'library_app:new_video' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">добавить</button>
	</form>
{% endblock %}

library_app/templates/library_app/view_all_books.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Просмотр добавленных книг.</h2>
	{% if db_info %}
		{% for book in db_info %}
			<h3><a href="{% url 'library_app:view_book' book.id %}">{{ book.title }}</a></h3>
			<p>Время публикаций: {{ book.publication_date }}</p>
		{% endfor %}
	{% else %}
		{{ error_info }}
	{% endif %}
{% endblock %}

library_app/templates/library_app/view_all_photos.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Просмотр добавленных видео.</h2>
	{% if db_info %}
		{% for photo in db_info %}
			<h2><a href="{% url 'library_app:view_photo' photo.id %}">{{ photo.title }}</a></h2>
			<p>Время публикаций: {{ photo.publication_date }}</p>
		{% endfor %}
	{% else %}
		{{ error_info }}
	{% endif %}
{% endblock %}

library_app/templates/library_app/view_all_songs.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Просмотр добавленных песен.</h2>
	{% if db_info %}
		{% for song in db_info %}
			<h2><a href="{% url 'library_app:view_song' song.id %}">{{ song.title }}</a></h2>
			<p>Время публикаций: {{ song.publication_date }}</p>
		{% endfor %}
	{% else %}
		{{ error_info }}
	{% endif %}
{% endblock %}

library_app/templates/library_app/view_all_videos.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>Просмотр добавленных видео.</h2>
	{% if db_info %}
		{% for video in db_info %}
			<h2><a href="{% url 'library_app:view_video' video.id %}">{{ video.title }}</a></h2>
			<p>Время публикаций: {{ video.publication_date }}</p>
		{% endfor %}
	{% else %}
		{{ error_info }}
	{% endif %}
{% endblock %}

library_app/templates/library_app/view_book.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>{{ book.title }}</h2>
{% endblock %}

library_app/templates/library_app/view_photo.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>{{ photo.title }}</h2>
{% endblock %}

library_app/templates/library_app/view_song.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>{{ song.title }}</h2>
{% endblock %}

library_app/templates/library_app/view_video.html
{% extends 'library_app/base.html' %}

{% block content %}
	<h2>{{ video.title }}</h2>
{% endblock %}